// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyfljkzlhitlmsvqvdwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5Zmxqa3psaGl0bG1zdnF2ZHdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNjI0ODcsImV4cCI6MjA3MjgzODQ4N30.iUtKRmUeJWfCXnnIyrte6pvTAGfl1MoHUgBAMsxFdOg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});